name: on_the_fly
description: "Auto convert files on the fly"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bitsdojo_window: ^0.1.6
  blurrycontainer: ^2.1.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_svg: ^1.1.6
  hugeicons: ^0.0.7
  image: ^4.3.0
  ionicons: ^0.2.2
  logging: ^1.3.0
  mesh: ^0.4.2
  meta: ^1.15.0
  path: ^1.9.0
  provider: ^6.1.2
  squadron: ^6.1.3
  url_launcher: ^6.3.1
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/illust/
  fonts:
    - family: Playfair Display
      fonts:
        - asset: fonts/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: fonts/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: fonts/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: fonts/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: fonts/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ThinItalic.ttf