name: build windows
on:
  workflow_dispatch:
    inputs:
      comments:
        description: "Comments"
        required: false
        default: "Nothing"
        type: string
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build_info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Worker Comments: $BUILD_CMTS"
        env:
          BUILD_CMTS: ${{ inputs.comments }}
  build_windows:
    runs-on: windows-latest
    steps:
      - name: "setup flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
      - uses: actions/checkout@v3
      - run: flutter --version
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs # this is just a simple check for the i18n stuffs
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: OnTheFly_Windows_x64
          path: ./build/windows
